// Generated by https://quicktype.io

export interface Acusacao {
    id:          number;
    tipificacao: number;
    descricao:   string;
    excluido:    boolean;
    usuario_id:  number;
    criado_em:   Date;
    alterado_em: Date;
}
