// Generated by https://quicktype.io

export interface Antecendente {
    id:          number;
    local:       string;
    data:        Date;
    hora:        string;
    descricao:   string;
    acusacao_id: number;
    usuario_id:  number;
    excluido:    boolean;
    criado_em:   Date;
    alterado_em: Date;
}
