// Generated by https://quicktype.io

export interface Criminoso {
    id:                   number;
    nome:                 string;
    alcunha:              string;
    telefone:             string;
    pai:                  string;
    mae:                  string;
    data_de_nascimento:   Date;
    obito:                boolean;
    foragido:             boolean;
    rg:                   string;
    cpf:                  string;
    naturalidade:         string;
    nacionalidade:        string;
    local_de_trabalho:    string;
    profissao:            string;
    estado_civil:         string;
    grau_de_escolaridade: string;
    genero:               string;
    altura:               string;
    etnia:                string;
    porte_fisico:         string;
    cor_dos_olhos:        string;
    cor_da_pele:          string;
    cor_do_cabelo:        string;
    tipo_de_cabelo:       string;
    foto_perfil_esquerdo: string;
    foto_perfil_direito:  string;
    foto_frente:          string;
    cep:                  string;
    rua:                  string;
    bairro:               string;
    numero:               number;
    complemento:          string;
    excluido:             boolean;
    usuario_id:           number;
    criado_em:            Date;
    alterado_em:          Date;
}
