// Generated by https://quicktype.io

export interface Marca {
    id:                   number;
    cicatriz_ou_tatuagem: string;
    descricao:            string;
    parte_do_corpo:       string;
    foto:                 string;
    tipo_de_tatuagem_id:  null;
    criminoso_id:         number;
    usuario_id:           number;
    excluido:             boolean;
    criado_em:            Date;
    alterado_em:          Date;
}
