// Generated by https://quicktype.io

export interface TipoTatuagem {
    id:          number;
    tipo:        string;
    usuario_id:  number;
    excluido:    boolean;
    criado_em:   Date;
    alterado_em: Date;
}
