// Generated by https://quicktype.io

export interface Usuario {
    id:                   number;
    usuario:              string;
    nome:                 string;
    ultimo_acesso:        Date;
    permissao_de_escrita: boolean;
    excluido:             boolean;
    criado_em:            Date;
    alterado_em:          Date;
}
